### ISSUE TITLE
Error througn log in

### ISSUE THREAD

**Issue by webornottoweb** [AlahmadiKw/wunderlist-utilities#1]
Hi, i'm clicking on Login button and nothing happens... white screen. Thank you

**Comment by AlahmadiQ8** [comment]
Hello @AndreyPalamarchuk  sorry for the late reply. I haven't been able to reproduce the issue. does it still exists?

**Comment by webornottoweb** [comment]
@AlahmadiQ8 no, now all is ok, thank you
